import { IMPOSSIBLE, VersionInfo } from '@start9labs/start-sdk'

export const current = VersionInfo.of({
  // <upstream version>:<package revision>
  // Upstream 0.3.0 — the operator-surface release. The package revision resets
  // to 0 with the upstream bump.
  version: '0.3.0:0',
  releaseNotes: {
    en_US:
      'Upstream rebuilds the operator surface as one product. The status page now opens with the verdict and four live tiles — links, traffic this run, members, uptime — instead of leading with the public key, and the members page gains a one-click **Copy invite** on each row, drops the stale “new invite” panel, folds revoked members away, and renames ROSTER to Member list. Both pages share a header and footer.\n\nThis package adds the two things that made any of it reachable: the members page is now its own **interface**, opened from Interfaces rather than by typing “admin/” onto the end of an address, and a new **Show Admin Token** action reveals the token that unlocks it — previously printed once to the log on the boot that minted it and unrecoverable after that.\n\nNote that on a LAN address the browser offers no clipboard, so Copy invite reveals the invite as selectable text instead. That is expected.',
    es_ES:
      'Upstream reconstruye la superficie del operador como un solo producto. La página de estado ahora empieza por el veredicto y cuatro indicadores en vivo —enlaces, tráfico de esta sesión, miembros y tiempo activo— en lugar de encabezar con la clave pública, y la página de miembros gana un botón **Copiar invitación** en cada fila, elimina el panel obsoleto de «invitación nueva», pliega los miembros revocados y renombra ROSTER como Lista de miembros. Ambas páginas comparten cabecera y pie.\n\nEste paquete añade lo que hacía falta para poder llegar a todo eso: la página de miembros es ahora su propia **interfaz**, que se abre desde Interfaces en vez de escribir «admin/» al final de una dirección, y la nueva acción **Mostrar el token de administración** revela el token que la desbloquea, que antes solo se imprimía una vez en el registro del arranque que lo generó.\n\nTen en cuenta que en una dirección de red local el navegador no ofrece portapapeles, así que Copiar invitación mostrará la invitación como texto seleccionable. Es lo esperado.',
    de_DE:
      'Upstream baut die Bedienoberfläche zu einem Produkt zusammen. Die Statusseite beginnt jetzt mit dem Ergebnis und vier Live-Kacheln — Verbindungen, Datenverkehr in diesem Lauf, Mitglieder, Laufzeit — statt mit dem öffentlichen Schlüssel, und die Mitgliederseite erhält pro Zeile ein **Einladung kopieren**, verliert das veraltete Feld „neue Einladung“, klappt widerrufene Mitglieder ein und benennt ROSTER in Mitgliederliste um. Beide Seiten teilen Kopf- und Fußzeile.\n\nDieses Paket ergänzt das, was all das überhaupt erreichbar macht: Die Mitgliederseite ist jetzt eine eigene **Schnittstelle**, die über „Schnittstellen“ geöffnet wird, statt „admin/“ an eine Adresse anzuhängen, und die neue Aktion **Admin-Token anzeigen** liefert das Token, das sie freischaltet — bisher nur einmal beim erzeugenden Start ins Log geschrieben und danach nicht mehr auffindbar.\n\nBeachte: Unter einer LAN-Adresse bietet der Browser keine Zwischenablage an, daher zeigt „Einladung kopieren“ die Einladung als markierbaren Text. Das ist so gewollt.',
    pl_PL:
      'Projekt upstream przebudował powierzchnię operatora w jeden spójny produkt. Strona stanu zaczyna się teraz od werdyktu i czterech kafelków na żywo — połączenia, ruch w tym uruchomieniu, członkowie, czas działania — zamiast od klucza publicznego, a strona członków zyskuje przycisk **Kopiuj zaproszenie** w każdym wierszu, traci nieaktualny panel „nowe zaproszenie”, zwija członków unieważnionych i zmienia nazwę ROSTER na Lista członków. Obie strony mają wspólny nagłówek i stopkę.\n\nTen pakiet dokłada to, dzięki czemu można tam w ogóle trafić: strona członków jest teraz osobnym **interfejsem**, otwieranym z zakładki Interfejsy zamiast dopisywania „admin/” do adresu, a nowa akcja **Pokaż token administracyjny** ujawnia token, który ją odblokowuje — wcześniej wypisywany jednorazowo do dziennika przy uruchomieniu, które go utworzyło.\n\nUwaga: pod adresem w sieci lokalnej przeglądarka nie udostępnia schowka, więc Kopiuj zaproszenie pokaże zaproszenie jako zaznaczalny tekst. Tak ma być.',
    fr_FR:
      'Le projet amont refait la surface d’administration en un seul produit. La page d’état s’ouvre désormais sur le verdict et quatre tuiles en direct — liens, trafic de cette session, membres, temps de fonctionnement — au lieu de commencer par la clé publique, et la page des membres gagne un bouton **Copier l’invitation** sur chaque ligne, perd le panneau obsolète « nouvelle invitation », replie les membres révoqués et renomme ROSTER en Liste des membres. Les deux pages partagent un en-tête et un pied de page.\n\nCe paquet ajoute ce qui rendait tout cela atteignable : la page des membres est maintenant une **interface** à part entière, ouverte depuis l’onglet Interfaces au lieu d’ajouter « admin/ » à une adresse, et la nouvelle action **Afficher le jeton d’administration** révèle le jeton qui la déverrouille — jusqu’ici écrit une seule fois dans le journal du démarrage qui l’avait généré.\n\nÀ noter : sur une adresse du réseau local, le navigateur ne propose pas de presse-papiers ; Copier l’invitation affiche donc l’invitation en texte sélectionnable. C’est le comportement attendu.',
  },
  migrations: {
    // Nothing to migrate. The operator surface is served from the image, on the
    // port it was already on; no route, response shape or auth rule changed in
    // 0.3.0. The roster, seed and admin token stay where upstream already keeps
    // them on the volume.
    up: async ({ effects }) => {},
    down: IMPOSSIBLE,
  },
})
