import { IMPOSSIBLE, VersionInfo } from '@start9labs/start-sdk'

export const current = VersionInfo.of({
  // <upstream version>:<package revision>
  // Upstream 0.4.0 plus untagged upstream fixes (shutdown, reachability re-probe and its logging), so the upstream
  // half stays 0.4.0 — that is what the relay reports — and the revision moves.
  version: '0.4.0:1',
  releaseNotes: {
    en_US:
      '**0.4.0:1** fixes two things seen on a live box. Stopping or restarting the relay no longer hangs for 15 seconds and exits with an error when a browser or proxy has an idle connection open to the status page. And a failing Internet Reachability check is now re-tested every 30 seconds instead of every second, so it no longer buries the relay’s own log lines. The relay also re-tests its own reachability while it is firewalled, after 10, 20 and 30 seconds, then 1, 2 and 5 minutes, then every 5 minutes: HyperDHT only tests once at startup, so a relay that came up red used to stay red until the next restart. Known issue: if you use an Outbound Gateway, StartOS does not re-apply it after an install or update, and the relay goes red because its traffic leaves through the wrong connection. Stop the service and start it again after updating; a Restart is not enough.\n\nThe relay can now be made **private** from StartOS. *Configure Relay* gains an **Access** setting: Public admits anyone with the relay key, Private admits only the people you have invited on the Members Page. Existing installs stay public until you change it.\n\nThere is no precondition for going private. With no members yet the relay lets nobody in, and the new **Access** health check and the status page both say so until you add someone. If people already use your relay, send their invites first — an invite works on a public relay too, so nobody is cut off when you switch.\n\nUpstream’s pages now follow the mode. A private relay’s status page points at invites and no longer offers a QR code of a key that cannot connect anyone, and the members page says plainly when invites are not yet gating the relay.\n\nThe Allowlist field is renamed **Static Keys (advanced)**: it cannot admit Mirall users, and was never the way to run a private relay for people.',
    es_ES:
      '**0.4.0:1** corrige dos problemas vistos en un servidor real. Detener o reiniciar el relé ya no se queda colgado 15 segundos ni termina con error cuando un navegador o un proxy mantiene abierta una conexión inactiva con la página de estado. Y una comprobación de Accesibilidad desde Internet fallida se repite ahora cada 30 segundos en lugar de cada segundo, de modo que ya no entierra las líneas de registro del propio relé. Además, el relé vuelve a comprobar su propia accesibilidad mientras figura como bloqueado, a los 10, 20 y 30 segundos, luego a 1, 2 y 5 minutos, y después cada 5 minutos: HyperDHT solo la comprueba una vez al arrancar, de modo que un relé que arrancaba en rojo seguía así hasta el siguiente reinicio. Problema conocido: si usas una puerta de enlace de salida, StartOS no la vuelve a aplicar tras una instalación o actualización, y el relé se pone en rojo porque su tráfico sale por la conexión equivocada. Detén el servicio y vuelve a iniciarlo después de actualizar; reiniciar no basta.\n\nEl relé ya puede hacerse **privado** desde StartOS. *Configurar el relé* incorpora el ajuste **Acceso**: Público admite a cualquiera con la clave del relé, Privado admite solo a quienes hayas invitado en la página de miembros. Las instalaciones existentes siguen siendo públicas hasta que lo cambies.\n\nNo hay requisito previo para hacerlo privado. Sin miembros, el relé no deja entrar a nadie, y la nueva comprobación de estado **Acceso** y la página de estado lo indican hasta que añadas a alguien. Si ya hay gente usando tu relé, envía primero sus invitaciones: una invitación también funciona en un relé público, así que nadie queda desconectado al cambiar.\n\nLas páginas de upstream siguen ahora el modo. La página de estado de un relé privado remite a las invitaciones y ya no ofrece un código QR de una clave que no conecta a nadie, y la página de miembros dice claramente cuándo las invitaciones aún no restringen el relé.\n\nEl campo Lista de permitidos pasa a llamarse **Claves estáticas (avanzado)**: no puede admitir a usuarios de Mirall y nunca fue la forma de tener un relé privado para personas.',
    de_DE:
      '**0.4.0:1** behebt zwei Probleme von einem echten Server. Das Stoppen oder Neustarten des Relays hängt nicht mehr 15 Sekunden und endet nicht mehr mit einem Fehler, wenn ein Browser oder Proxy eine ungenutzte Verbindung zur Statusseite offen hält. Und eine fehlgeschlagene Prüfung der Internet-Erreichbarkeit wird jetzt alle 30 Sekunden statt jede Sekunde wiederholt, sodass sie die eigenen Logzeilen des Relays nicht mehr überdeckt. Außerdem prüft das Relay seine Erreichbarkeit jetzt selbst erneut, solange es als blockiert gilt, nach 10, 20 und 30 Sekunden, dann nach 1, 2 und 5 Minuten, danach alle 5 Minuten: HyperDHT prüft nur einmal beim Start, sodass ein Relay, das rot startete, bis zum nächsten Neustart rot blieb. Bekanntes Problem: Wenn du ein Outbound Gateway nutzt, wendet StartOS es nach einer Installation oder Aktualisierung nicht erneut an, und das Relay wird rot, weil sein Datenverkehr über die falsche Verbindung hinausgeht. Stoppe den Dienst nach dem Aktualisieren und starte ihn wieder; ein Neustart genügt nicht.\n\nDas Relay lässt sich jetzt in StartOS **privat** schalten. *Relay konfigurieren* erhält die Einstellung **Zugang**: Öffentlich lässt jeden mit dem Relay-Schlüssel zu, Privat nur Personen, die du auf der Mitgliederseite eingeladen hast. Bestehende Installationen bleiben öffentlich, bis du es änderst.\n\nFür das Umschalten auf Privat gibt es keine Vorbedingung. Ohne Mitglieder lässt das Relay niemanden herein, und die neue Zustandsprüfung **Zugang** sowie die Statusseite sagen das, bis du jemanden hinzufügst. Wenn dein Relay bereits genutzt wird, verschicke zuerst die Einladungen — eine Einladung funktioniert auch auf einem öffentlichen Relay, sodass beim Umschalten niemand getrennt wird.\n\nDie Seiten von Upstream richten sich jetzt nach dem Modus. Die Statusseite eines privaten Relays verweist auf Einladungen und bietet keinen QR-Code mehr für einen Schlüssel an, mit dem sich niemand verbinden kann, und die Mitgliederseite sagt deutlich, wenn Einladungen das Relay noch nicht beschränken.\n\nDas Feld Zulassungsliste heißt jetzt **Statische Schlüssel (erweitert)**: Es kann keine Mirall-Nutzer zulassen und war nie der Weg zu einem privaten Relay für Personen.',
    pl_PL:
      '**0.4.0:1** naprawia dwa problemy zauważone na działającym serwerze. Zatrzymanie lub ponowne uruchomienie przekaźnika nie zawiesza się już na 15 sekund i nie kończy błędem, gdy przeglądarka lub serwer pośredniczący trzyma otwarte bezczynne połączenie ze stroną stanu. A nieudana kontrola osiągalności z Internetu jest teraz ponawiana co 30 sekund zamiast co sekundę, więc nie zasypuje już własnych wpisów dziennika przekaźnika. Przekaźnik ponawia też sam test własnej osiągalności, dopóki uchodzi za zablokowany, po 10, 20 i 30 sekundach, potem po 1, 2 i 5 minutach, a następnie co 5 minut: HyperDHT sprawdza ją tylko raz przy starcie, więc przekaźnik, który wystartował na czerwono, pozostawał taki aż do kolejnego restartu. Znany problem: jeśli używasz bramy wychodzącej, StartOS nie stosuje jej ponownie po instalacji lub aktualizacji i przekaźnik świeci na czerwono, bo jego ruch wychodzi niewłaściwym łączem. Po aktualizacji zatrzymaj usługę i uruchom ją ponownie; samo ponowne uruchomienie nie wystarczy.\n\nPrzekaźnik można teraz ustawić jako **prywatny** z poziomu StartOS. *Konfiguruj przekaźnik* zyskuje ustawienie **Dostęp**: Publiczny dopuszcza każdego, kto ma klucz przekaźnika, Prywatny tylko osoby zaproszone na stronie członków. Istniejące instalacje pozostają publiczne, dopóki tego nie zmienisz.\n\nPrzejście na tryb prywatny nie ma warunków wstępnych. Bez członków przekaźnik nie wpuszcza nikogo, a nowa kontrola stanu **Dostęp** i strona stanu mówią o tym, dopóki kogoś nie dodasz. Jeśli z przekaźnika już ktoś korzysta, najpierw roześlij zaproszenia — zaproszenie działa także na przekaźniku publicznym, więc przełączenie nikogo nie rozłączy.\n\nStrony projektu upstream dostosowują się teraz do trybu. Strona stanu prywatnego przekaźnika kieruje do zaproszeń i nie pokazuje już kodu QR klucza, którym nikt się nie połączy, a strona członków jasno informuje, kiedy zaproszenia jeszcze nie ograniczają dostępu.\n\nPole Lista dozwolonych nazywa się teraz **Klucze statyczne (zaawansowane)**: nie pozwala dopuścić użytkowników Mirall i nigdy nie było sposobem na prywatny przekaźnik dla ludzi.',
    fr_FR:
      '**0.4.0:1** corrige deux problèmes constatés sur un serveur réel. L’arrêt ou le redémarrage du relais ne reste plus bloqué 15 secondes et ne se termine plus en erreur lorsqu’un navigateur ou un proxy garde ouverte une connexion inactive vers la page d’état. Et un contrôle d’accessibilité depuis Internet en échec est désormais relancé toutes les 30 secondes au lieu de chaque seconde, ce qui n’enfouit plus les lignes de journal du relais lui-même. Le relais reteste aussi lui-même son accessibilité tant qu’il est considéré comme bloqué, après 10, 20 et 30 secondes, puis 1, 2 et 5 minutes, puis toutes les 5 minutes : HyperDHT ne la teste qu’une fois au démarrage, si bien qu’un relais démarré au rouge le restait jusqu’au redémarrage suivant. Problème connu : si vous utilisez une passerelle sortante, StartOS ne la réapplique pas après une installation ou une mise à jour, et le relais passe au rouge parce que son trafic sort par la mauvaise connexion. Arrêtez le service puis démarrez-le après la mise à jour ; un redémarrage ne suffit pas.\n\nLe relais peut désormais être rendu **privé** depuis StartOS. *Configurer le relais* gagne un réglage **Accès** : Public admet toute personne ayant la clé du relais, Privé uniquement les personnes invitées sur la page des membres. Les installations existantes restent publiques tant que vous ne le changez pas.\n\nIl n’y a aucune condition préalable pour passer en privé. Sans membre, le relais ne laisse entrer personne, et le nouveau contrôle d’état **Accès** ainsi que la page d’état le disent jusqu’à ce que vous ajoutiez quelqu’un. Si votre relais est déjà utilisé, envoyez d’abord les invitations — une invitation fonctionne aussi sur un relais public, donc personne n’est coupé lors du changement.\n\nLes pages du projet amont suivent maintenant le mode. La page d’état d’un relais privé renvoie vers les invitations et ne propose plus le QR code d’une clé qui ne connecte personne, et la page des membres indique clairement quand les invitations ne filtrent pas encore le relais.\n\nLe champ Liste d’autorisation devient **Clés statiques (avancé)** : il ne peut pas admettre d’utilisateurs de Mirall et n’a jamais été le moyen d’avoir un relais privé pour des personnes.',
  },
  migrations: {
    // Nothing to migrate. store.json's new `access` key defaults to 'open', which
    // is the mode every earlier install was already running in.
    up: async ({ effects }) => {},
    down: IMPOSSIBLE,
  },
})
